# Generated by Django 3.2 on 2021-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('birthDate', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
            ],
        ),
    ]
