# Generated by Django 3.2.3 on 2021-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_auto_20210522_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('state_id', models.IntegerField()),
            ],
        ),
    ]
